# Generated by Django 4.2.7 on 2023-11-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default-book.png', upload_to='books/'),
        ),
    ]
